# ============================================================================ #
# Author: Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
apiVersion: v1
kind: Service
metadata:
  name: pg-nginx-pod-service
spec:
  selector:
    app: pg-nginx-pod
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30003
  type: NodePort
# ============================================================================ #
