# ============================================================================ #
# Authors:
# - Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
# A local helm chart, from this repo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paul-grozav/gtp_library
    targetRevision: main
    path: k8s/argocd/helm_charts/app_two
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: replicaCount
        # These values need to be strings
        value: "7"
  destination:
    server: https://kubernetes.default.svc
    namespace: app-two
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
# ============================================================================ #
# Nginx - a public helm chart pulled from their repo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-webserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 20.1.0
    chart: nginx
    helm:
      values: |
        image:
          # Specific Nginx image tag
          tag: 1.29.0-debian-12-r2
        replicaCount: 1
        service:
          type: ClusterIP
          port: 80
        resources:
          requests: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: my-nginx-webserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
# ============================================================================ #
# KubeView - A read-only visual diagram of K8s objects
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-webserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://code.benco.io/kubeview/deploy/helm
    targetRevision: 2.0.3
    chart: kubeview
    helm:
      values: |
        image:
          # Specific Nginx image tag
          tag: 1.29.0-debian-12-r2
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
# ============================================================================ #
