# ============================================================================ #
# Authors:
# - Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-one
  # This should be the NS where ArgoCD is running
  namespace: apps-argocd
spec:
  destination:
    # Keep this value for the cluster ArgoCD is running in
    server: https://kubernetes.default.svc
    # Namespace where we want to install our application
    namespace: app-one-ns
  # This default project is created at ArgoCD install time. Useful for RBAC
  project: default
  source:
    # repoURL: https://github.com/argoproj/argocd-example-apps
    # targetRevision: HEAD
    # path: guestbook
    repoURL: https://github.com/paul-grozav/gtp_library
    targetRevision: main
    path: k8s/argocd/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    # Create the target namespace if it doesn't exist
    - CreateNamespace=true
# ============================================================================ #
