# ============================================================================ #
# Authors:
# - Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app_one
  # This should be the NS where ArgoCD is running
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    # Namespace where we want to install our application
    namespace: app_1_ns
  project: my-project
  source:
    # repoURL: https://github.com/argoproj/argocd-example-apps
    # targetRevision: HEAD
    # path: guestbook
    repoURL: https://github.com/paul-grozav/gtp_library
    targetRevision: main
    path: k8s/argocd/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
# ============================================================================ #
