# ============================================================================ #
# Authors:
# - Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paul-conf
data:
  paul.conf: |
    This is just a test file {{ .Values.replicaCount }}
# ============================================================================ #